[mgr]
show_hidden = true

[opener]
edit = [
  { run = 'nvim %*', desc = "Nvim all selected", block = true, for = "windows" },
  { run = 'nvim %n', desc = "Nvim N-th selected", block = true, for = "windows" },
  { run = 'nvim %0', desc = "Nvim hovered", block = true, for = "windows" },
]
reveal = [
  { run = 'xdg-open "$(dirname "$1")"', desc = "Reveal", for = "linux" },
  { run = 'open -R "$1"', desc = "Reveal", for = "macos" },
  { run = 'explorer /select,"%1"', orphan = true, desc = "Reveal", for = "windows" },
  { run = 'termux-open "$(dirname "$1")"', desc = "Reveal", for = "android" },
  { run = '''clear; exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]
open = [
  { run = 'xdg-open "$1"', desc = "Open", for = "linux" },
  { run = 'open "$@"', desc = "Open", for = "macos" },
  { run = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
  { run = 'termux-open "$1"', desc = "Open", for = "android" },
]

[open]
rules = [
  # Folder
  { name = "*/", use = [
    "edit",
    "open",
    "reveal",
  ] },
  # Text
  { mime = "text/*", use = [
    "edit",
    "reveal",
  ] },
  # Image
  { mime = "image/*", use = [
    "open",
    "reveal",
  ] },
  # Media
  { mime = "{audio,video}/*", use = [
    "play",
    "reveal",
  ] },
  # Archive
  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [
    "extract",
    "reveal",
  ] },
  # JSON
  { mime = "application/{json,ndjson}", use = [
    "edit",
    "reveal",
  ] },
  { mime = "*/javascript", use = [
    "edit",
    "reveal",
  ] },
  { name = "*.toml", use = [
    "edit",
    "reveal",
  ] },
  # Empty file
  { mime = "inode/empty", use = [
    "edit",
    "reveal",
  ] },
  # Fallback
  { name = "*", use = [
    "open",
    "reveal",
  ] },
]
