[".oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/fzf-tab"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab"
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    refreshPeriod = "168h"
    [".oh-my-zsh/custom/themes/powerlevel10k".clone]
      args = ["--depth=1"]

[".tmux"]
    type = "git-repo"
    url = "https://github.com/gpakosz/.tmux.git"
    refreshPeriod = "168h"
[".rofi-translate"]
    type = "git-repo"
    url = "https://github.com/JackTheMico/rofi-translate"
    refreshPeriod = "168h"
[".rofi-systemd"]
    type = "git-repo"
    url = "https://github.com/IvanMalison/rofi-systemd.git"
    refreshPeriod = "168h"
[".config/ranger/plugins/zoxide"]
    type = "git-repo"
    url = "https://github.com/jchook/ranger-zoxide.git"
    refreshPeriod = "168h"
[".forgit"]
    type = "git-repo"
    url = "https://github.com/wfxr/forgit.git"
    refreshPeriod = "168h"
[".local/bin/kubectl"]
    type = "file"
    url = "https://s3.us-west-2.amazonaws.com/amazon-eks/1.22.6/2022-03-09/bin/linux/amd64/kubectl"
    refreshPeriod = "168h"

