[".config/yazi/plugins/searchjump.yazi/main.lua"]
  type = "file"
  url = "https://raw.githubusercontent.com/DreamMaoMao/yazi-config/refs/heads/master/plugins/searchjump.yazi/main.lua"
  refreshPeriod = "168h"
[".config/qutebrowser/catppuccin"]
  type = "git-repo"
  url = "https://github.com/catppuccin/qutebrowser.git"
  refreshPeriod = "168h"
[".config/doom/modules/editor/meow"]
  type = "git-repo"
  url = "git@github.com:JackTheMico/doom-meow.git"
  refreshPeriod = "168h"
