# 继承基础配置
include kitty.conf

# 覆盖字体设置：使用霞鹜文楷等宽与 24pt 字号
font_family      LXGW WenKai Mono Screen
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size        32.0

# 压缩字间距（如果觉得偏紧或偏宽，可以调整为 85% 或 75%）
modify_font cell_width 65%
