gui:
  mainPanelSplitMode: 'horizontal'
  language: 'en'
  theme:
    activeBorderColor:
      - bold
      - '#696fd7'
    optionsTextColor:
      - magenta
    selectedLineBgColor:
      - '#ae9053'
      # - reverse
git:
  commit:
    signOff: true
