gui:
  mainPanelSplitMode: 'horizontal'
  language: 'en'
  theme:
    activeBorderColor:
      - bold
      - '#696fd7'
    optionsTextColor:
      - magenta
    selectedLineBgColor:
      - '#ae9053'
      # - reverse
git:
  commit:
    signOff: true
update:
  method: prompt # can be: prompt | background | never
  days: 14 # how often an update is checked for
