[data]
    gmailwork = "jack@fireworkhq.com"
    gmailpersonal = "dlwxxxdlw@gmail.com"
[git]
    autoCommit = true
    autoPush = true
[gpg]
    recipient = "Jack Deng"
[merge]
    command = "lvim"
    args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]
